pipeline {
    agent any
    stages {
        stage('compile') {
	         steps {
                echo 'compiling..'
		            git url: 'https://github.com/Guruprasad9738/samplejavaapp-lerndevops'
		            sh script: '/usr/share/maven/bin/mvn compile'
           }
        }
        stage('codereview-pmd') {
	         steps {
                echo 'codereview..'
		            sh script: '/usr/share/maven/bin/mvn -P metrics pmd:pmd'
           }
	         post {
               success {
		             recordIssues enabledForFailure: true, tool: pmdParser(pattern: '**/target/pmd.xml')
               }
           }		
        }
        stage('unit-test') {
	         steps {
                echo 'unittest..'
      	        sh script: '/usr/share/maven/bin/mvn test'
                 }
	          post {
               success {
                   junit 'target/surefire-reports/*.xml'
               }
           }			
        }
        stage('package') {
	         steps {
                echo 'package......'
		            sh script: '/usr/share/maven/bin/mvn package'	
           }		
        }
    }
}
